# Clustering Semantico dei Report di Insicurezza Alimentare (IPC)

Questo notebook implementa una pipeline avanzata per il caricamento, la pulizia, l'embedding denso e il clustering semantico dei report IPC.  
L'obiettivo è raggruppare le situazioni di crisi in base alla tipologia di insicurezza alimentare e ai driver che le causano (es. conflitti, siccità, crisi economiche), indipendentemente dal paese.

La pipeline è progettata per essere eseguita sulla **GPU di Google Colab** e include:
1. Setup dell'ambiente (Montaggio Drive e installazione delle librerie).
2. Caricamento e pulizia dei testi (rimozione dell'intestazione metadati).
3. Generazione di embedding con **Instructor-Large** (`hkunlp/instructor-large`), un modello avanzato esplicitamente ottimizzato per seguire istruzioni arbitrarie per compiti come il clustering.
4. Riduzione dimensionale con **UMAP** (5D per clustering, 2D per visualizzazione).
5. Clustering con **K-Means** (e scelta ottimale di K con metriche geometriche come *Silhouette Score* e *Davies-Bouldin Index*) e **HDBSCAN**.
6. **Validazione della Coerenza Semantica**:
   - **Lemmatizzazione (NLTK)** e rimozione dei nomi dei paesi nel TF-IDF per parole chiave pulite.
   - **Tabella di Contingenza** (Paese vs. Cluster) ed entropia geografica per escludere il bias geografico.
   - **LLM-as-a-Judge** (tramite API Mistral) per descrivere i cluster e valutarne la coerenza semantica.
7. Visualizzazione interattiva 2D con **Plotly**.

## 1. Setup dell'Ambiente e Importazione Librerie

In [4]:
import pandas as pd
df = pd.read_csv("df_duplicati.csv")
df

,Unnamed: 0,nome_file,paese,periodo,inizio_periodo,fine_periodo,testo_originale,gruppo,Llama_3_2_3B_anonimo,Llama_3_1_8B_anonimo,Llama_3_1_8B_8bit_anonimo
0,7,El_Salvador_Mar_2025_-_Feb_2026_KeyResults.txt,El Salvador,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]:\nThe affected areas are ...
1,9,Honduras_Mar_2025_-_Feb_2026_KeyResults.txt,Honduras,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]:\nThe affected areas are ...
2,23,Guatemala_Mar_2025_-_Feb_2026_KeyResults.txt,Guatemala,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]: \nThe affected areas are...
3,31,El_Salvador_Jun_2020_-_Aug_2020_KeyResults.txt,El Salvador,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, clima..."
4,35,Honduras_Jun_2020_-_Aug_2020_KeyResults.txt,Honduras,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe affected areas are ...
5,59,Guatemala_Jun_2020_-_Aug_2020_KeyResults.txt,Guatemala,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, clima..."
6,68,El_Salvador_Jun_2022_-_Aug_2022_KeyResults.txt,El Salvador,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
7,70,Honduras_Jun_2022_-_Aug_2022_KeyResults.txt,Honduras,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
8,74,Guatemala_Jun_2022_-_Aug_2022_KeyResults.txt,Guatemala,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
9,162,El_Salvador_Nov_2018_-_Apr_2019_KeyResults.txt,El Salvador,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
10,167,Honduras_Nov_2018_-_Apr_2019_KeyResults.txt,Honduras,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, limit..."
11,170,Guatemala_Feb_2023_-_Jan_2024_KeyResults.txt,Guatemala,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
12,175,El_Salvador_Feb_2023_-_Jan_2024_KeyResults.txt,El Salvador,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
13,179,Guatemala_Nov_2018_-_Apr_2019_KeyResults.txt,Guatemala,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
14,180,Honduras_Feb_2023_-_Jan_2024_KeyResults.txt,Honduras,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
15,191,Guatemala_Feb_2018_-_Aug_2018_KeyResults.txt,Guatemala,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, limit..."
16,210,El_Salvador_Feb_2018_-_Aug_2018_KeyResults.txt,El Salvador,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, limit..."
17,214,Honduras_Feb_2018_-_Aug_2018_KeyResults.txt,Honduras,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
18,327,El_Salvador_Oct_2020_-_Aug_2021_KeyResults.txt,El Salvador,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
19,329,El_Salvador_Mar_2024_-_Feb_2025_KeyResults.txt,El Salvador,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nDecreased purchasing p...
20,331,Honduras_Oct_2020_-_Aug_2021_KeyResults.txt,Honduras,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
21,332,Honduras_Mar_2024_-_Feb_2025_KeyResults.txt,Honduras,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]: \nThe affected areas are...
22,355,Guatemala_Mar_2024_-_Feb_2025_KeyResults.txt,Guatemala,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nDecreased purchasing p...
23,358,Guatemala_Oct_2020_-_Aug_2021_KeyResults.txt,Guatemala,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
24,364,Guatemala_Nov_2021_-_Aug_2022_KeyResults.txt,Guatemala,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...
25,373,El_Salvador_Apr_2026_-_Mar_2027_KeyResults.txt,El Salvador,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",8.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe situation is prima...,[SHOCKS AND DRIVERS]: \nThe situation is prima...
26,376,Honduras_Apr_2026_-_Mar_2027_KeyResults.txt,Honduras,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",8.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe situation is prima...,[SHOCKS AND DRIVERS]: \nThe situation is prima...
27,389,Honduras_Nov_2021_-_Aug_2022_KeyResults.txt,Honduras,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...
28,394,El_Salvador_Nov_2021_-_Aug_2022_KeyResults.txt,El Salvador,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
29,399,Honduras_Jun_2021_-_Aug_2021_KeyResults.txt,Honduras,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
30,404,El_Salvador_Jun_2021_-_Aug_2021_KeyResults.txt,El Salvador,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...
31,410,Guatemala_Oct_2019_-_May_2020_KeyResults.txt,Guatemala,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
32,418,El_Salvador_Oct_2019_-_May_2020_KeyResults.txt,El Salvador,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
33,423,Honduras_Oct_2019_-_May_2020_KeyResults.txt,Honduras,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
34,427,Guatemala_Jun_2021_-_Aug_2021_KeyResults.txt,Guatemala,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...

In [5]:
# 1.3 Import delle librerie necessarie
import re
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
import umap
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import pairwise_distances_argmin_min
import plotly.express as px
import torch
import scipy.stats as stats
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

# Impostiamo il seed per la riproducibilità dei risultati
np.random.seed(42)

# Download delle risorse NLTK per la lemmatizzazione
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet = True)
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)
nltk.download('stopwords', quiet=True)
print("NLTK e librerie importate correttamente.")

NLTK e librerie importate correttamente.

## 3. Generazione degli Embedding con Modello Instructor-Large (GPU)

Utilizziamo il modello **`hkunlp/instructor-large`**. Questo modello è stato esplicitamente addestrato per seguire istruzioni di testo arbitrarie per compiti come il clustering, formattate come coppie di `[istruzione, testo]`. Questo ci consente di guidare lo spazio semantico a focalizzarsi sui driver delle crisi e sulle condizioni di insicurezza alimentare.

In [6]:
df.columns

Index(['Unnamed: 0', 'nome_file', 'paese', 'periodo', 'inizio_periodo',
       'fine_periodo', 'testo_originale', 'gruppo', 'Llama_3_2_3B_anonimo',
       'Llama_3_1_8B_anonimo', 'Llama_3_1_8B_8bit_anonimo'],
      dtype='object')

In [7]:
# 1.1 Monta Google Drive per accedere ai file dei report
#from google.colab import drive
import os
import pandas as pd

DRIVE_PATH = "./"
colonne_target = ['Llama_3_2_3B_anonimo', 'Llama_3_1_8B_anonimo', 'Llama_3_1_8B_8bit_anonimo']
for colonna_target in colonne_target:
    TESTO_DIR = df[colonna_target]


    # 3.1 Caricamento del modello Instructor-Large
    # 3.1 Caricamento del modello GTE-Large
    import torch
    from sentence_transformers import SentenceTransformer
    import einops

    # 1. Rilevamento corretto dell'acceleratore Apple Silicon (Metal Performance Shaders)
    MODEL_NAME = "nomic-ai/nomic-embed-text-v1.5"
    device = "mps" if torch.backends.mps.is_available() else "cpu"
    print(f"Caricamento modello {MODEL_NAME} su dispositivo: {device}...")

    # 2. Inizializzazione con disattivazione del padding dinamico incompatibile con macOS
    model = SentenceTransformer(
        MODEL_NAME,
        device=device,
        trust_remote_code=True,
    )

    # Definiamo l'istruzione per orientare il clustering esplicitamente sui driver
    istruzione = "search_document: "

    # Il modello GTE richiede la concatenazione diretta dell'istruzione e del testo
    testi_con_istruzione = [istruzione + t for t in df[colonna_target]]

    print("Generazione degli embedding in corso...")
    embeddings = model.encode(testi_con_istruzione, normalize_embeddings=True, show_progress_bar=True)
    print(f"Embedding generati! Shape: {embeddings.shape}")

    # Salva gli embedding su Drive per riutilizzarli senza rigenerarli
    np.save(os.path.join(DRIVE_PATH, "embeddings_report_anonimi.npy"), embeddings)
    df.to_parquet(os.path.join(DRIVE_PATH, "metadata_report_anonimi.parquet"))
    print("Embedding e metadati salvati correttamente")

    # 4.1 Riduzione dimensionale con UMAP
    print("UMAP a 5 dimensioni per il clustering...")
    reducer_clustering = umap.UMAP(
        n_neighbors=15,
        min_dist=0.0,
        n_components=5,
        metric="cosine",
        random_state=42
    )
    embeddings_5d = reducer_clustering.fit_transform(embeddings)

    print("UMAP a 2 dimensioni per la visualizzazione...")
    reducer_visualization = umap.UMAP(
        n_neighbors=15,
        min_dist=0.1,
        n_components=2,
        metric="cosine",
        random_state=42
    )
    embeddings_2d = reducer_visualization.fit_transform(embeddings)

    # Inserimento coordinate UMAP nel dataframe
    df[f"x_{colonna_target}"] = embeddings_2d[:, 0]
    df[f"y_{colonna_target}"] = embeddings_2d[:, 1]

    # Salva gli embedding ridotti
    np.save(os.path.join(DRIVE_PATH, "embeddings_umap5d_report_anonimi.npy"), embeddings_5d)
    print("Riduzione dimensionale completata e salvata.")

    # 5.1.1 Valutazione geometrica su range di K
    inertie = []
    silhouette = []
    davies_bouldin = []
    K_range = range(2, 13)

    for k in K_range:
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = km.fit_predict(embeddings_5d)
        inertie.append(km.inertia_)
        silhouette.append(silhouette_score(embeddings_5d, labels))
        davies_bouldin.append(davies_bouldin_score(embeddings_5d, labels))


    # 5.2.1 Esecuzione HDBSCAN
    import hdbscan

    print("Calcolo dei cluster con HDBSCAN...")
    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=15,
        min_samples=5,
        metric="manhattan"
    )
    hdbscan_labels = clusterer.fit_predict(embeddings_5d)
    df[f"cluster_hdbscan_{colonna_target}"] = hdbscan_labels

    n_clusters_hdb = len(set(hdbscan_labels)) - (1 if -1 in hdbscan_labels else 0)
    n_noise_hdb = list(hdbscan_labels).count(-1)

Caricamento modello nomic-ai/nomic-embed-text-v1.5 su dispositivo: mps...

<All keys matched successfully>

Generazione degli embedding in corso...

Batches: 100%|██████████| 2/2 [00:00<00:00,  2.49it/s]
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Embedding generati! Shape: (35, 768)
Embedding e metadati salvati correttamente
UMAP a 5 dimensioni per il clustering...
UMAP a 2 dimensioni per la visualizzazione...
Riduzione dimensionale completata e salvata.
Calcolo dei cluster con HDBSCAN...
Caricamento modello nomic-ai/nomic-embed-text-v1.5 su dispositivo: mps...

/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
<All keys matched successfully>

Generazione degli embedding in corso...

Batches: 100%|██████████| 2/2 [00:01<00:00,  1.86it/s]
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

Embedding generati! Shape: (35, 768)
Embedding e metadati salvati correttamente
UMAP a 5 dimensioni per il clustering...
UMAP a 2 dimensioni per la visualizzazione...
Riduzione dimensionale completata e salvata.
Calcolo dei cluster con HDBSCAN...
Caricamento modello nomic-ai/nomic-embed-text-v1.5 su dispositivo: mps...

<All keys matched successfully>

Generazione degli embedding in corso...

Batches: 100%|██████████| 2/2 [00:00<00:00,  2.55it/s]

Embedding generati! Shape: (35, 768)
Embedding e metadati salvati correttamente
UMAP a 5 dimensioni per il clustering...
UMAP a 2 dimensioni per la visualizzazione...
Riduzione dimensionale completata e salvata.
Calcolo dei cluster con HDBSCAN...

/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/nlp_clustering/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [16]:
# 1. Isola le colonne target per pulizia del codice
colonne_cluster = [
    'cluster_hdbscan_Llama_3_2_3B_anonimo',
    'cluster_hdbscan_Llama_3_1_8B_anonimo',
    'cluster_hdbscan_Llama_3_1_8B_8bit_anonimo'
]

# 2. Esegui l'aggregazione quantitativa (Consigliata per dataset estesi)
df_omogeneita = df.groupby('gruppo')[colonne_cluster].nunique()
df_omogeneita

,cluster_hdbscan_Llama_3_2_3B_anonimo,cluster_hdbscan_Llama_3_1_8B_anonimo,cluster_hdbscan_Llama_3_1_8B_8bit_anonimo
gruppo,,,
0.0,1,1,1
1.0,1,1,1
2.0,1,1,1
3.0,1,1,1
4.0,1,1,1
5.0,1,1,1
6.0,1,1,1
7.0,1,1,1
8.0,1,1,1
9.0,1,1,1
10.0,1,1,1
11.0,1,1,1

In [14]:
df

,Unnamed: 0,nome_file,paese,periodo,inizio_periodo,fine_periodo,testo_originale,gruppo,Llama_3_2_3B_anonimo,Llama_3_1_8B_anonimo,Llama_3_1_8B_8bit_anonimo,x_Llama_3_2_3B_anonimo,y_Llama_3_2_3B_anonimo,cluster_hdbscan_Llama_3_2_3B_anonimo,x_Llama_3_1_8B_anonimo,y_Llama_3_1_8B_anonimo,cluster_hdbscan_Llama_3_1_8B_anonimo,x_Llama_3_1_8B_8bit_anonimo,y_Llama_3_1_8B_8bit_anonimo,cluster_hdbscan_Llama_3_1_8B_8bit_anonimo
0,7,El_Salvador_Mar_2025_-_Feb_2026_KeyResults.txt,El Salvador,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]:\nThe affected areas are ...,3.917336,-3.092032,-1,9.441715,10.410748,-1,-0.227834,0.174096,-1
1,9,Honduras_Mar_2025_-_Feb_2026_KeyResults.txt,Honduras,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]:\nThe affected areas are ...,4.112453,-2.786137,-1,9.706458,10.707183,-1,0.066581,0.411465,-1
2,23,Guatemala_Mar_2025_-_Feb_2026_KeyResults.txt,Guatemala,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,3.591251,-2.895066,-1,9.169412,10.781019,-1,-0.015570,-0.002199,-1
3,31,El_Salvador_Jun_2020_-_Aug_2020_KeyResults.txt,El Salvador,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, clima...",5.537043,-3.007756,-1,8.240951,5.654067,-1,1.204649,1.661024,-1
4,35,Honduras_Jun_2020_-_Aug_2020_KeyResults.txt,Honduras,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe affected areas are ...,5.504407,-2.785540,-1,8.011463,5.353070,-1,1.156667,2.146925,-1
5,59,Guatemala_Jun_2020_-_Aug_2020_KeyResults.txt,Guatemala,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, clima...",5.713109,-2.487803,-1,8.393112,5.451568,-1,1.431447,1.377671,-1
6,68,El_Salvador_Jun_2022_-_Aug_2022_KeyResults.txt,El Salvador,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.734009,-5.699531,-1,10.257873,10.286038,-1,0.897304,-0.299562,-1
7,70,Honduras_Jun_2022_-_Aug_2022_KeyResults.txt,Honduras,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.353041,-5.934326,-1,10.116608,9.866429,-1,0.764319,-0.924527,-1
8,74,Guatemala_Jun_2022_-_Aug_2022_KeyResults.txt,Guatemala,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.378244,-5.514226,-1,10.505216,10.086431,-1,1.290647,-0.529590,-1
9,162,El_Salvador_Nov_2018_-_Apr_2019_KeyResults.txt,El Salvador,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.701977,-6.443059,-1,11.491268,10.030187,-1,1.666361,-1.437751,-1
10,167,Honduras_Nov_2018_-_Apr_2019_KeyResults.txt,Honduras,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, limit...",3.656403,-6.162446,-1,6.724604,5.032629,-1,1.484648,-1.855821,-1
11,170,Guatemala_Feb_2023_-_Jan_2024_KeyResults.txt,Guatemala,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.109431,-4.590805,-1,10.785840,8.788825,-1,0.230574,-1.530470,-1
12,175,El_Salvador_Feb_2023_-_Jan_2024_KeyResults.txt,El Salvador,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.815847,-4.171228,-1,10.597874,9.152680,-1,0.408267,-1.350018,-1
13,179,Guatemala_Nov_2018_-_Apr_2019_KeyResults.txt,Guatemala,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.189347,-6.279535,-1,6.591989,5.565957,-1,1.282765,-1.654853,-1
14,180,Honduras_Feb_2023_-_Jan_2024_KeyResults.txt,Honduras,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.236090,-4.205277,-1,10.287521,8.910678,-1,-0.031418,-1.752680,-1
15,191,Guatemala_Feb_2018_-_Aug_2018_KeyResults.txt,Guatemala,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, limit...",2.922415,-6.656868,-1,11.088896,10.282237,-1,1.857475,-2.112183,-1
16,210,El_Salvador_Feb_2018_-_Aug_2018_KeyResults.txt,El Salvador,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,"[SHOCKS AND DRIVERS]:\nEconomic factors, limit...",4.195580,-6.213716,-1,11.158686,9.793477,-1,1.969998,-1.769445,-1
17,214,Honduras_Feb_2018_-_Aug_2018_KeyResults.txt,Honduras,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.478008,-6.751856,-1,11.468147,9.629173,-1,2.051938,-1.457732,-1
18,327,El_Salvador_Oct_2020_-_Aug_2021_KeyResults.txt,El Salvador,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,5.371433,-3.543040,-1,7.212104,5.386928,-1,1.460012,2.493463,-1
19,329,El_Salvador_Mar_2024_-_Feb_2025_KeyResults.txt,El Salvador,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nDecreased purchasing p...,3.426572,-4.981642,-1,11.226422,8.938466,-1,0.084479,-0.702461,-1
20,331,Honduras_Oct_2020_-_Aug_2021_KeyResults.txt,Honduras,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,4.825537,-3.709480,-1,6.955140,5.200107,-1,0.982821,2.571706,-1
21,332,Honduras_Mar_2024_-_Feb_2025_KeyResults.txt,Honduras,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,2.765225,-4.813260,-1,9.506879,10.937704,-1,0.289763,-0.107218,-1
22,355,Guatemala_Mar_2024_-_Feb_2025_KeyResults.txt,Guatemala,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nDecreased purchasing p...,2.264006,-4.946999,-1,10.546070,9.569203,-1,0.477804,-0.489504,-1
23,358,Guatemala_Oct_2020_-_Aug_2021_KeyResults.txt,Guatemala,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,5.055824,-3.948272,-1,7.188266,4.821885,-1,0.762733,1.960572,-1
24,364,Guatemala_Nov_2021_-_Aug_2022_KeyResults.txt,Guatemala,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe affected areas are...,4.059320,-4.717181,-1,9.680481,8.021195,-1,-1.054625,-0.827053,-1
25,373,El_Salvador_Apr_2026_-_Mar_2027_KeyResults.txt,El Salvador,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",8.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe situation is prima...,[SHOCKS AND DRIVERS]: \nThe situation is prima...,2.937934,-5.116385,-1,9.613847,9.198885,-1,-0.311255,-1.257666,-1
26,376,Honduras_Apr_2026_-_Mar_2027_KeyResults.txt,Honduras,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",8.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe situation is prima...,[SHOCKS AND DRIVERS]: \nThe situation is prima...,2.241868,-4.402541,-1,9.439421,9.657758,-1,-0.620810,0.020063,-1
27,389,Honduras_Nov_2021_-_Aug_2022_KeyResults.txt,Honduras,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...,4.562677,-4.913445,-1,9.353874,7.708358,-1,-0.889466,-1.378689,-1
28,394,El_Salvador_Nov_2021_-_Aug_2022_KeyResults.txt,El Salvador,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,4.492864,-4.428804,-1,10.045340,8.084424,-1,-0.633036,-1.087618,-1
29,399,Honduras_Jun_2021_-_Aug_2021_KeyResults.txt,Honduras,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,5.304732,-2.122936,-1,7.775316,4.775463,-1,1.968238,1.843191,-1
30,404,El_Salvador_Jun_2021_-_Aug_2021_KeyResults.txt,El Salvador,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...,5.005018,-2.748130,-1,7.891409,4.913848,-1,1.753052,1.659215,-1
31,410,Guatemala_Oct_2019_-_May_2020_KeyResults.txt,Guatemala,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,6.137057,-3.467991,-1,7.815036,6.307462,-1,2.310814,2.644461,-1
32,418,El_Salvador_Oct_2019_-_May_2020_KeyResults.txt,El Salvador,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,6.266038,-3.143273,-1,7.347871,6.447425,-1,2.131150,2.875267,-1
33,423,Honduras_Oct_2019_-_May_2020_KeyResults.txt,Honduras,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,6.151005,-2.977136,-1,7.482103,6.073689,-1,2.490484,2.547169,-1
34,427,Guatemala_Jun_2021_-_Aug_2021_KeyResults.txt,Guatemala,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,[SHOCKS AND DRIVERS]:\nThe underlying causes o...,5.087822,-2.354642,-1,7.647146,5.205598,-1,1.860803,2.234594,-1