In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../dataset_report_anonimizzati_llama_cpp.csv")

In [3]:
df

,nome_file,paese,periodo,inizio_periodo,fine_periodo,testo_originale,report_anonimo
0,Gaza_Strip_Sep_2024_-_Apr_2025_KeyResults.txt,Gaza Strip,Sep 2024 / Apr 2025,Sep 2024,Apr 2025,"One year into the conflict, the risk of Famine...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...
1,Afghanistan_Apr_2020_-_Nov_2020_KeyResults.txt,Afghanistan,Apr 2020 / Nov 2020,Apr 2020,Nov 2020,Food insecurity remains alarmingly high in Afg...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
2,Afghanistan_Nov_2017_-_Feb_2018_KeyResults.txt,Afghanistan,Nov 2017 / Feb 2018,Nov 2017,Feb 2018,"During the 2017 post-harvest season, 33% of th...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...
3,South_Sudan_Sep_2018_-_Mar_2019_KeyResults.txt,South Sudan,Sep 2018 / Mar 2019,Sep 2018,Mar 2019,"Based on the September IPC analysis, it is exp...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...
4,Mozambique_Jun_2020_-_Sep_2020_KeyResults.txt,Mozambique,Jun 2020 / Sep 2020,Jun 2020,Sep 2020,The results of this Acute Food Insecurity pilo...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
...,...,...,...,...,...,...,...
492,Haiti_Aug_2023_-_Jun_2024_KeyResults.txt,Haiti,Aug 2023 / Jun 2024,Aug 2023,Jun 2024,About 4.35 million people are experiencing hig...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
493,Djibouti_Mar_2022_-_Dec_2022_KeyResults.txt,Djibouti,Mar 2022 / Dec 2022,Mar 2022,Dec 2022,For the current analysis period of March throu...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
494,Djibouti_May_2013_-_May_2013_KeyResults.txt,Djibouti,May 2013 / May 2013,May 2013,May 2013,Food availability in the Republic of Djibouti ...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...
495,Madagascar_Sep_2024_-_Aug_2025_KeyResults.txt,Madagascar,Sep 2024 / Aug 2025,Sep 2024,Aug 2025,"Between September and December 2024, around 1....",[SHOCKS AND DRIVERS]: \nThe underlying causes ...
496,Lesotho_May_2025_-_Mar_2026_KeyResults.txt,Lesotho,May 2025 / Mar 2026,May 2025,Mar 2026,"More than 258,000 people living in rural areas...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...

In [4]:
lista_testi_duplicati = df[df["testo_originale"].duplicated()]["testo_originale"].unique().tolist()

In [5]:
for testo, gruppo in zip(lista_testi_duplicati, range(len(lista_testi_duplicati))):
    df.loc[df["testo_originale"] == testo, "gruppo"] = gruppo

In [6]:
df_duplicati = df[df["gruppo"].notnull()]
df_duplicati

,nome_file,paese,periodo,inizio_periodo,fine_periodo,testo_originale,report_anonimo,gruppo
7,El_Salvador_Mar_2025_-_Feb_2026_KeyResults.txt,El Salvador,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,0.0
9,Honduras_Mar_2025_-_Feb_2026_KeyResults.txt,Honduras,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,0.0
23,Guatemala_Mar_2025_-_Feb_2026_KeyResults.txt,Guatemala,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,0.0
31,El_Salvador_Jun_2020_-_Aug_2020_KeyResults.txt,El Salvador,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,1.0
35,Honduras_Jun_2020_-_Aug_2020_KeyResults.txt,Honduras,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,1.0
59,Guatemala_Jun_2020_-_Aug_2020_KeyResults.txt,Guatemala,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,1.0
68,El_Salvador_Jun_2022_-_Aug_2022_KeyResults.txt,El Salvador,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.0
70,Honduras_Jun_2022_-_Aug_2022_KeyResults.txt,Honduras,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.0
74,Guatemala_Jun_2022_-_Aug_2022_KeyResults.txt,Guatemala,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,2.0
162,El_Salvador_Nov_2018_-_Apr_2019_KeyResults.txt,El Salvador,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.0
167,Honduras_Nov_2018_-_Apr_2019_KeyResults.txt,Honduras,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.0
170,Guatemala_Feb_2023_-_Jan_2024_KeyResults.txt,Guatemala,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,4.0
175,El_Salvador_Feb_2023_-_Jan_2024_KeyResults.txt,El Salvador,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,4.0
179,Guatemala_Nov_2018_-_Apr_2019_KeyResults.txt,Guatemala,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,3.0
180,Honduras_Feb_2023_-_Jan_2024_KeyResults.txt,Honduras,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,4.0
191,Guatemala_Feb_2018_-_Aug_2018_KeyResults.txt,Guatemala,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,5.0
210,El_Salvador_Feb_2018_-_Aug_2018_KeyResults.txt,El Salvador,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,5.0
214,Honduras_Feb_2018_-_Aug_2018_KeyResults.txt,Honduras,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,5.0
327,El_Salvador_Oct_2020_-_Aug_2021_KeyResults.txt,El Salvador,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,6.0
329,El_Salvador_Mar_2024_-_Feb_2025_KeyResults.txt,El Salvador,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,7.0
331,Honduras_Oct_2020_-_Aug_2021_KeyResults.txt,Honduras,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,6.0
332,Honduras_Mar_2024_-_Feb_2025_KeyResults.txt,Honduras,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,7.0
355,Guatemala_Mar_2024_-_Feb_2025_KeyResults.txt,Guatemala,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,7.0
358,Guatemala_Oct_2020_-_Aug_2021_KeyResults.txt,Guatemala,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,6.0
364,Guatemala_Nov_2021_-_Aug_2022_KeyResults.txt,Guatemala,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,9.0
373,El_Salvador_Apr_2026_-_Mar_2027_KeyResults.txt,El Salvador,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,8.0
376,Honduras_Apr_2026_-_Mar_2027_KeyResults.txt,Honduras,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,8.0
389,Honduras_Nov_2021_-_Aug_2022_KeyResults.txt,Honduras,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,9.0
394,El_Salvador_Nov_2021_-_Aug_2022_KeyResults.txt,El Salvador,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",[SHOCKS AND DRIVERS]: \nThe underlying causes ...,9.0
399,Honduras_Jun_2021_-_Aug_2021_KeyResults.txt,Honduras,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,10.0
404,El_Salvador_Jun_2021_-_Aug_2021_KeyResults.txt,El Salvador,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,10.0
410,Guatemala_Oct_2019_-_May_2020_KeyResults.txt,Guatemala,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,11.0
418,El_Salvador_Oct_2019_-_May_2020_KeyResults.txt,El Salvador,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,11.0
423,Honduras_Oct_2019_-_May_2020_KeyResults.txt,Honduras,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,11.0
427,Guatemala_Jun_2021_-_Aug_2021_KeyResults.txt,Guatemala,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,[SHOCKS AND DRIVERS]: \nThe underlying causes ...,10.0

In [7]:
df_duplicati = df_duplicati.drop(columns=["report_anonimo"])
df_duplicati

,nome_file,paese,periodo,inizio_periodo,fine_periodo,testo_originale,gruppo
7,El_Salvador_Mar_2025_-_Feb_2026_KeyResults.txt,El Salvador,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0
9,Honduras_Mar_2025_-_Feb_2026_KeyResults.txt,Honduras,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0
23,Guatemala_Mar_2025_-_Feb_2026_KeyResults.txt,Guatemala,Mar 2025 / Feb 2026,Mar 2025,Feb 2026,"During the current period (March to May 2025),...",0.0
31,El_Salvador_Jun_2020_-_Aug_2020_KeyResults.txt,El Salvador,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0
35,Honduras_Jun_2020_-_Aug_2020_KeyResults.txt,Honduras,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0
59,Guatemala_Jun_2020_-_Aug_2020_KeyResults.txt,Guatemala,Jun 2020 / Aug 2020,Jun 2020,Aug 2020,"Overview\nFrom June to August 2020, the period...",1.0
68,El_Salvador_Jun_2022_-_Aug_2022_KeyResults.txt,El Salvador,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0
70,Honduras_Jun_2022_-_Aug_2022_KeyResults.txt,Honduras,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0
74,Guatemala_Jun_2022_-_Aug_2022_KeyResults.txt,Guatemala,Jun 2022 / Aug 2022,Jun 2022,Aug 2022,Since several months have passed since the sec...,2.0
162,El_Salvador_Nov_2018_-_Apr_2019_KeyResults.txt,El Salvador,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0
167,Honduras_Nov_2018_-_Apr_2019_KeyResults.txt,Honduras,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0
170,Guatemala_Feb_2023_-_Jan_2024_KeyResults.txt,Guatemala,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0
175,El_Salvador_Feb_2023_-_Jan_2024_KeyResults.txt,El Salvador,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0
179,Guatemala_Nov_2018_-_Apr_2019_KeyResults.txt,Guatemala,Nov 2018 / Apr 2019,Nov 2018,Apr 2019,The Tri-national Border Federation of Río Lemp...,3.0
180,Honduras_Feb_2023_-_Jan_2024_KeyResults.txt,Honduras,Feb 2023 / Jan 2024,Feb 2023,Jan 2024,During the current period of February to May 2...,4.0
191,Guatemala_Feb_2018_-_Aug_2018_KeyResults.txt,Guatemala,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0
210,El_Salvador_Feb_2018_-_Aug_2018_KeyResults.txt,El Salvador,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0
214,Honduras_Feb_2018_-_Aug_2018_KeyResults.txt,Honduras,Feb 2018 / Aug 2018,Feb 2018,Aug 2018,The Tri-national Border Federation of Río Lemp...,5.0
327,El_Salvador_Oct_2020_-_Aug_2021_KeyResults.txt,El Salvador,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0
329,El_Salvador_Mar_2024_-_Feb_2025_KeyResults.txt,El Salvador,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0
331,Honduras_Oct_2020_-_Aug_2021_KeyResults.txt,Honduras,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0
332,Honduras_Mar_2024_-_Feb_2025_KeyResults.txt,Honduras,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0
355,Guatemala_Mar_2024_-_Feb_2025_KeyResults.txt,Guatemala,Mar 2024 / Feb 2025,Mar 2024,Feb 2025,During the current period of March to June 202...,7.0
358,Guatemala_Oct_2020_-_Aug_2021_KeyResults.txt,Guatemala,Oct 2020 / Aug 2021,Oct 2020,Aug 2021,Overview\nBetween October 2020 and February 20...,6.0
364,Guatemala_Nov_2021_-_Aug_2022_KeyResults.txt,Guatemala,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0
373,El_Salvador_Apr_2026_-_Mar_2027_KeyResults.txt,El Salvador,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",8.0
376,Honduras_Apr_2026_-_Mar_2027_KeyResults.txt,Honduras,Apr 2026 / Mar 2027,Apr 2026,Mar 2027,"From April to June 2026, an estimated 113,000 ...",8.0
389,Honduras_Nov_2021_-_Aug_2022_KeyResults.txt,Honduras,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0
394,El_Salvador_Nov_2021_-_Aug_2022_KeyResults.txt,El Salvador,Nov 2021 / Aug 2022,Nov 2021,Aug 2022,"The current period, November 2021 to February ...",9.0
399,Honduras_Jun_2021_-_Aug_2021_KeyResults.txt,Honduras,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0
404,El_Salvador_Jun_2021_-_Aug_2021_KeyResults.txt,El Salvador,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0
410,Guatemala_Oct_2019_-_May_2020_KeyResults.txt,Guatemala,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0
418,El_Salvador_Oct_2019_-_May_2020_KeyResults.txt,El Salvador,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0
423,Honduras_Oct_2019_-_May_2020_KeyResults.txt,Honduras,Oct 2019 / May 2020,Oct 2019,May 2020,OVERVIEW\n17% of the population of the Tri-Nat...,11.0
427,Guatemala_Jun_2021_-_Aug_2021_KeyResults.txt,Guatemala,Jun 2021 / Aug 2021,Jun 2021,Aug 2021,This acute food insecurity analysis was an upd...,10.0

In [8]:
df_duplicati.to_csv("df_duplicati.csv")